// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqgjaprlrlcfqxziuasz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZ2phcHJscmxjZnF4eml1YXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDE0ODAsImV4cCI6MjA2Nzc3NzQ4MH0.iyAakBi-8BuYCaZqnJgm6UO4ljo97SQEs34ewpCPCAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});